name: PostUpdateTask

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, reopened ]
    branches:
      - 'feature/base-auto-update'

jobs:
  postupgradetask:
    if: ${{ startsWith(github.head_ref, 'renovate/quarkus') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.head_ref
        run: echo ${{ github.head_ref }}

      - name: Parse branch name
        id: parse
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          GROUPID=$(echo $BRANCH | cut -d'/' -f2 | cut -d'-' -f1)
          NEW_BRANCH=$(echo $BRANCH | cut -d'/' -f2 )
          GROUPID=$(echo "${GROUPID^}")
          echo "GROUPID=$GROUPID" >> "$GITHUB_OUTPUT"
          echo "NEW_BRANCH=$NEW_BRANCH" >> "$GITHUB_OUTPUT"
          
          echo "DEPNAME=$(echo $BRANCH | cut -d'/' -f2 | cut -d'_' -f1)" >> "$GITHUB_OUTPUT"
          echo "CURR_VERSION=$(echo $BRANCH | cut -d'/' -f2 | cut -d'_' -f2)" >> "$GITHUB_OUTPUT"
          echo "NEW_VERSION=$(echo $BRANCH | cut -d'/' -f2 | cut -d'_' -f3)" >> "$GITHUB_OUTPUT"

      - name: echo parsed values
        env:
          GROUPID: ${{ steps.parse.outputs.GROUPID }}
          DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
          CURR_VERSION: ${{ steps.parse.outputs.CURR_VERSION }}
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: echo "groupId=${GROUPID}, depname=${DEPNAME}, currVersion=${CURR_VERSION}, newVersion=${NEW_VERSION}"

      - uses: actions/checkout@v4
        name: checkout
        with:
          ref: feature/base-auto-update

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Upgrade
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROUPID: ${{ steps.parse.outputs.GROUPID }}
        if: "!startsWith(github.head_ref, 'renovate/quarkus')"
        run: |
          ls -al
          java --version
          mvn --version
          echo "TODO: call openrewrite recipe"
          mvn rewrite:run -Drecipe=com.gepardec.update.${GROUPID} -Popenrewrite -s .m2/settings.xml

      - name: Upgrade Quarkus
        env:
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        if: "startsWith(github.head_ref, 'renovate/quarkus')"
        run: |
          ls -al
          mvn --version
          java --version
          yes | mvn io.quarkus.platform:quarkus-maven-plugin:${NEW_VERSION}:update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          title: Autoupdate ${{ steps.parse.outputs.GROUPID }}
          branch: autoupdate/${{ steps.parse.outputs.NEW_BRANCH }}
          base: feature/base-auto-update
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          body: |
            Upgrade from ${{ steps.parse.outputs.NEW_BRANCH }}